ball:
  chroma blue:
  - 56
  - 90
  chroma red:
  - 131
  - 157
  luma:
  - 46
  - 131
field:
  chroma blue:
  - 0
  - 64
  chroma red:
  - 164
  - 227
  luma:
  - 80
  - 181
goal A:
  chroma blue:
  - 98
  - 123
  chroma red:
  - 124
  - 146
  luma:
  - 40
  - 77
goal B:
  chroma blue:
  - 82
  - 95
  chroma red:
  - 163
  - 177
  luma:
  - 70
  - 115
