ball:
  chroma blue:
  - 51
  - 80
  chroma red:
  - 140
  - 169
  luma:
  - 41
  - 145
field:
  chroma blue:
  - 0
  - 53
  chroma red:
  - 164
  - 227
  luma:
  - 69
  - 181
goal A:
  chroma blue:
  - 102
  - 114
  chroma red:
  - 135
  - 156
  luma:
  - 38
  - 102
goal B:
  chroma blue:
  - 82
  - 95
  chroma red:
  - 163
  - 177
  luma:
  - 70
  - 115
