ball:
  chroma blue:
  - 60
  - 78
  chroma red:
  - 143
  - 152
  luma:
  - 112
  - 172
field:
  chroma blue:
  - 26
  - 77
  chroma red:
  - 181
  - 255
  luma:
  - 14
  - 255
goal A:
  chroma blue:
  - 99
  - 132
  chroma red:
  - 115
  - 157
  luma:
  - 44
  - 120
goal B:
  chroma blue:
  - 84
  - 120
  chroma red:
  - 163
  - 193
  luma:
  - 74
  - 136
