ball:
  chroma blue:
  - 55
  - 78
  chroma red:
  - 138
  - 158
  luma:
  - 62
  - 146
field:
  chroma blue:
  - 0
  - 64
  chroma red:
  - 164
  - 227
  luma:
  - 80
  - 182
goal A:
  chroma blue:
  - 102
  - 114
  chroma red:
  - 135
  - 156
  luma:
  - 38
  - 102
goal B:
  chroma blue:
  - 82
  - 95
  chroma red:
  - 163
  - 177
  luma:
  - 70
  - 115
