ball:
  chroma blue:
  - 16
  - 60
  chroma red:
  - 115
  - 142
  luma:
  - 113
  - 173
field:
  chroma blue:
  - 0
  - 55
  chroma red:
  - 164
  - 227
  luma:
  - 42
  - 255
goal A:
  chroma blue:
  - 75
  - 138
  chroma red:
  - 101
  - 142
  luma:
  - 59
  - 133
goal B:
  chroma blue:
  - 44
  - 83
  chroma red:
  - 175
  - 212
  luma:
  - 97
  - 162
