ball:
  chroma blue:
  - 20
  - 45
  chroma red:
  - 110
  - 145
  luma:
  - 95
  - 208
field:
  chroma blue:
  - 0
  - 55
  chroma red:
  - 164
  - 227
  luma:
  - 42
  - 255
goal A:
  chroma blue:
  - 88
  - 124
  chroma red:
  - 122
  - 142
  luma:
  - 17
  - 102
goal B:
  chroma blue:
  - 44
  - 44
  chroma red:
  - 126
  - 212
  luma:
  - 97
  - 162
