ball:
  chroma blue:
  - 24
  - 45
  chroma red:
  - 128
  - 146
  luma:
  - 138
  - 208
field:
  chroma blue:
  - 0
  - 55
  chroma red:
  - 164
  - 227
  luma:
  - 42
  - 255
goal A:
  chroma blue:
  - 88
  - 118
  chroma red:
  - 98
  - 150
  luma:
  - 41
  - 195
goal B:
  chroma blue:
  - 44
  - 44
  chroma red:
  - 126
  - 212
  luma:
  - 97
  - 162
