ball:
  chroma blue:
  - 60
  - 78
  chroma red:
  - 143
  - 152
  luma:
  - 112
  - 172
field:
  chroma blue:
  - 26
  - 77
  chroma red:
  - 181
  - 255
  luma:
  - 14
  - 255
goal A:
  chroma blue:
  - 100
  - 142
  chroma red:
  - 83
  - 157
  luma:
  - 41
  - 141
goal B:
  chroma blue:
  - 85
  - 116
  chroma red:
  - 149
  - 179
  luma:
  - 84
  - 142
