ball:
  chroma blue:
  - 16
  - 55
  chroma red:
  - 115
  - 147
  luma:
  - 111
  - 176
field:
  chroma blue:
  - 0
  - 55
  chroma red:
  - 164
  - 227
  luma:
  - 42
  - 255
goal A:
  chroma blue:
  - 99
  - 156
  chroma red:
  - 92
  - 157
  luma:
  - 20
  - 255
goal B:
  chroma blue:
  - 44
  - 44
  chroma red:
  - 175
  - 212
  luma:
  - 97
  - 162
