---
- name: ROS apt-key
  apt_key:
    url: "{{ ros_apt_key }}"
    state: present

- name: ROS repository
  apt_repository:
    repo: "deb {{ ros_apt_uri }} {{ ansible_lsb.codename }} main"
    state: present

- name: Update
  become: true
  apt: update-cache=yes

# left it as a bash command to pipe the output to a file,
# as ansible has no realtime log showing
- name: Install ROS, (could be around 2GB install)
  shell: |
    apt install ros-{{ ros_release }}-{{ ros_package }} -y > ros_install.log
  args:
      executable: /bin/bash

- name: Initialize rosdep
  shell: |
    sudo rosdep init
    rosdep update
  args:
      executable: /bin/bash

- name: Install pip3 packages
  become: true
  pip: name={{ item }} executable=pip3
  with_items:
    - rospkg

- name: ROS environment setup
  lineinfile:
    path: /etc/bash.bashrc
    line: 'source /opt/ros/{{ ros_release }}/setup.bash'
